-- v28: Import / upsert ThaiFCD-derived foods from local seed files.
--
-- Sources:
--   * ingredient.txt  -> cleangoal.foods (canonical_food_type raw_ingredient)
--   * beverage.xlsx   -> cleangoal.foods (beverage) + cleangoal.beverages row
--
-- Generated by: backend/scripts/generate_v28_thaifcd_migration.py
-- Idempotent via ON CONFLICT (food_name) DO UPDATE.

BEGIN;

SET search_path TO cleangoal, public;

DO $ensure_food_name_uq$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_foods_food_name'
      AND conrelid = 'cleangoal.foods'::regclass
  ) THEN
    ALTER TABLE cleangoal.foods
      ADD CONSTRAINT uq_foods_food_name UNIQUE (food_name);
  END IF;
END
$ensure_food_name_uq$;

-- Dedicated taxonomy buckets (avoid clashing ad-hoc category rows).
INSERT INTO cleangoal.dish_categories (category_name, canonical_food_type, display_order, description)
VALUES
    ('ThaiFCD import — วัตถุดิบ', 'raw_ingredient'::cleangoal.food_type, 990, 'Imported from ingredient.txt seed'),
    ('ThaiFCD import — เครื่องดื่ม', 'beverage'::cleangoal.food_type, 991, 'Imported from beverage.xlsx (per 100 ml)')
ON CONFLICT (category_name, canonical_food_type) DO NOTHING;

-- ─── Ingredients: dishes + foods ───────────────────────────────────────────

-- Dishes per ingredient food_name

INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กบ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กบ, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กบ, หนัง, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กบ, แห้ง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กิ้งก่า, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กุนเชียง, หมู, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กุนเชียง, หมู, ไร้มัน, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'งูเห่า, แห้ง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ลูกชิ้น, หมู, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ลูกชิ้น, ไก่, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ลูกชิ้นแคะ, เนื้อผสม (หมู, กุ้ง, ปลา) ผสมเต้าหู้ขาว, นึ่ง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ลูกชิ้นแคะ, เนื้อผสม (หมู, กุ้ง, ปลา) ผสมเต้าหู้ทอด, นึง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ลูกชิ้นแคะ, เนื้อผสม (หมู, กุ้ง, ปลา), นิ่ง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'วัว, ดับ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'วัว, เนื้อ, ติดมัน, ต้มเปื่อย',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'วัว, เนื้อ, ติดมัน, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'วัว, เนื้อ, บด, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'วัว, เนื้อ, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หนาง, หมู',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, คอ, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, คอ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, คอ, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, ซี่โครง, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, ซี่โครง, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, ซี่โครง, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, ดับ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, ยอ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สันนอก, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สันนอก, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สันใน, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สับ, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สับ, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สับ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สามชั้น, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สามชั้น, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, สามชั้น, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, หัว, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, หัวใจ, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, หัวใจ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมู, ไส้, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมูกรอบ (หมูสามชั้น ทอดกรอบ)',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมูทุบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมูสวรรค์',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมูหยอง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมูแดง, สุก',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมูแดดเดียว, ปิ้ง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หมูแผ่น',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'หม่า, หมู',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'อึ้ง, แห้ง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เขียด, แห้ง, รวมกระดูก',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เนื้อสวรรค์',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เนื้อแดดเดียว, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เป็ด, ขา, สุก',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เป็ด, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เป็ด, เนื้อ, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'แคบหมู',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'แคบหมู, ไม่มีมัน',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'แย้, ย่าง, รวมกระดูก',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'แย้, แห้ง, รวมกระดูก',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'แฮม, หมู, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'แฮม, ไก่, รมควัน',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, กัน, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ข้อเข่า, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ข้อเข่า, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ตับ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ตุ่น',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ทั้งตัว, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, น่อง, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, น่อง, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, บด, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ปีก, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ปีก, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ปีก, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, สะโพก, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, สะโพก, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, สะโพก, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, หนัง, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, อก, รวมหนัง, ต้ม',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, อก, รวมหนัง, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, เนื้อ, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่, โครง, ชุปแป้งทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่ป่า, ปีก, เนื้อและหนัง ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่ป่า, สะโพก, เนื้อและ หนัง, ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่ป่า, อก, เนื้อและหนัง ดิบ',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่ยอ, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่หยอง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไก่เชียง, ทอด, ไม่ใส่นำมัน',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไส้กรอก, หมู, ทอด',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ไส้ถั่ว, ย่าง',
       dc.dish_category_id,
       'raw_ingredient'::cleangoal.food_type,
       'Thai',
       'ThaiFCD ingredient seed'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — วัตถุดิบ'
  AND dc.canonical_food_type = 'raw_ingredient'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;

-- Ingredients foods batch 1/2

INSERT INTO cleangoal.foods (
    food_name, food_type, calories, protein, carbs, fat, sodium, sugar, cholesterol, fiber_g,
    serving_quantity, serving_unit_id, dish_id,
    updated_at
)
SELECT
    v.food_name,
    'raw_ingredient'::cleangoal.food_type,
    v.calories, v.protein, v.carbs, v.fat, v.sodium, v.sugar, v.cholesterol,
    COALESCE(v.fiber_g, 0),
    v.serving_quantity,
    (SELECT unit_id FROM cleangoal.units WHERE lower(name) = 'g' LIMIT 1),
    d.dish_id,
    NOW()
FROM (
    VALUES
('กบ, ทอด', 250, 34.28, 2.69, 11.4, 108, 0, 76, 0, 100),
('กบ, ย่าง', 352, 75.1, 0, 5.7, 621, 0, NULL, 0, 100),
('กบ, หนัง, ทอด', 551, 64.8, 0, 32.43, 1638, 0, NULL, 0, 100),
('กบ, แห้ง', 238, 51.2, 0, 3.7, 2047, 0, NULL, 0, 100),
('กิ้งก่า, ย่าง', 259, 55.1, 1.2, 3.8, 55, 0, NULL, 0, 100),
('กุนเชียง, หมู, ทอด', 513, 14.05, 37.89, 33.82, 1276, 0, 39, 0.2, 100),
('กุนเชียง, หมู, ไร้มัน, ทอด', 514, 15.14, 36.81, 33.99, NULL, 0, NULL, NULL, 100),
('งูเห่า, แห้ง', 384, 68.7, 21.9, 2.4, 421, 0, NULL, 0, 100),
('ลูกชิ้น, หมู, ทอด', 174, 14.73, 9.17, 8.73, NULL, 0, NULL, NULL, 100),
('ลูกชิ้น, ไก่, ทอด', 188, 15.1, 7.2, 11, NULL, 0, NULL, NULL, 100),
('ลูกชิ้นแคะ, เนื้อผสม (หมู, กุ้ง, ปลา) ผสมเต้าหู้ขาว, นึ่ง', 176, 13.2, 5.9, 11.1, NULL, 0, NULL, NULL, 100),
('ลูกชิ้นแคะ, เนื้อผสม (หมู, กุ้ง, ปลา) ผสมเต้าหู้ทอด, นึง', 272, 9.9, 15, 19.2, NULL, 0, NULL, NULL, 100),
('ลูกชิ้นแคะ, เนื้อผสม (หมู, กุ้ง, ปลา), นิ่ง', 244, 11.6, 13, 16.2, NULL, 0, NULL, NULL, 100),
('วัว, ดับ, ทอด', 245, 28.44, 7.64, 11.24, 936, 0, 350, 0, 100),
('วัว, เนื้อ, ติดมัน, ต้มเปื่อย', 220, 25.3, 0, 13.23, 311, 0, NULL, 0, 100),
('วัว, เนื้อ, ติดมัน, ทอด', 412, 46.1, 7.5, 21.9, NULL, 0, NULL, 0, 100),
('วัว, เนื้อ, บด, ย่าง', 239, 26.7, 0.3, 14.3, 486, 0, NULL, 1.2, 100),
('วัว, เนื้อ, ย่าง', 263, 28.6, 0.8, 15.8, 437, 0, NULL, 1.5, 100),
('หนาง, หมู', 176, 3.3, 6, 15.4, NULL, 0, NULL, NULL, 100),
('หมู, คอ, ดิบ', 189, 18.4, 0, 12.8, 45, 0, 38, 0, 100),
('หมู, คอ, ทอด', 296, 35, 2.4, 16.3, 120, 0, 62, 0, 100),
('หมู, คอ, ย่าง', 284, 35.9, 3.6, 14, 150, 0, 77, 0, 100),
('หมู, ซี่โครง, ดิบ', 208, 18.9, 0, 14.7, 100, 0, 47, 0, 100),
('หมู, ซี่โครง, ต้ม', 276, 25.8, 0.9, 18.8, 73, 0, 65, 0, 100),
('หมู, ซี่โครง, ทอด', 333, 33.7, 2.3, 21, 210, 0, 57, 0, 100),
('หมู, ดับ, ทอด', 268, 33.2, 4.6, 13, 120, 0, 290, 0, 100),
('หมู, ยอ', 293, 14.89, 2.85, 24.66, NULL, 0, NULL, NULL, 100),
('หมู, สันนอก, ต้ม', 204, 33, 0, 7.9, NULL, 0, NULL, NULL, 100),
('หมู, สันนอก, ทอด', 292, 30.89, 9.98, 14.24, NULL, 0, NULL, NULL, 100),
('หมู, สันใน, ทอด', 243, 37.2, 0, 10.5, NULL, 0, NULL, NULL, 100),
('หมู, สับ, ดิบ', 229, 18.2, 0.7, 17, NULL, 0, NULL, NULL, 100),
('หมู, สับ, ต้ม', 231, 24.4, 0, 14.8, NULL, 0, NULL, NULL, 100),
('หมู, สับ, ทอด', 333, 30.5, 0.3, 23.3, NULL, 0, NULL, NULL, 100),
('หมู, สามชั้น, ดิบ', 369, 14.23, 1.3, 34.07, NULL, 0, NULL, NULL, 100),
('หมู, สามชั้น, ต้ม', 428, 21.1, 0, 38.2, NULL, 0, NULL, NULL, 100),
('หมู, สามชั้น, ทอด', 450, 23.89, 6.24, 36.65, NULL, 0, NULL, NULL, 100),
('หมู, หัว, ต้ม', 316, 22.63, 6.07, 22.37, NULL, 0, NULL, NULL, 100),
('หมู, หัวใจ, ต้ม', 189, 28.1, 1.3, 7.9, NULL, 0, NULL, NULL, 100),
('หมู, หัวใจ, ทอด', 235, 30.6, 2.3, 11.5, NULL, 0, NULL, NULL, 100),
('หมู, ไส้, ดิบ', 205, 9.3, 2.4, 17.57, NULL, 0, NULL, NULL, 100),
('หมูกรอบ (หมูสามชั้น ทอดกรอบ)', 502, 19.9, 0, 46.9, NULL, 0, NULL, NULL, 100),
('หมูทุบ', 360, 48, 30.5, 5.1, NULL, 0, NULL, NULL, 100),
('หมูสวรรค์', 380, 34, 43.8, 7.6, NULL, 0, NULL, NULL, 100),
('หมูหยอง', 381, 38.59, 44.72, 5.32, NULL, 0, NULL, NULL, 100),
('หมูแดง, สุก', 335, 24.3, 6.2, 23.7, NULL, 0, NULL, NULL, 100),
('หมูแดดเดียว, ปิ้ง', 303, 39.11, 14.22, 10.01, NULL, 0, NULL, NULL, 100),
('หมูแผ่น', 419, 36.46, 42.96, 11.21, NULL, 0, NULL, NULL, 100),
('หม่า, หมู', 207, 25.3, 4.1, 9.9, NULL, 0, NULL, NULL, 100),
('อึ้ง, แห้ง', 457, 55.6, 10.4, 21.5, NULL, 0, NULL, NULL, 100),
('เขียด, แห้ง, รวมกระดูก', 316, 61.8, 2.3, 6.6, 1219, 0, NULL, 0, 100),
('เนื้อสวรรค์', 336, 38, 34.93, 4.97, NULL, 0, NULL, NULL, 100),
('เนื้อแดดเดียว, ทอด', 324, 45.18, 7.05, 12.74, NULL, 0, NULL, NULL, 100),
('เป็ด, ขา, สุก', 181, 12.4, 6.5, 11.7, 331, 0, NULL, 0, 100),
('เป็ด, ย่าง', 299, 20.8, 3.6, 22.4, 179, 0, NULL, 0, 100),
('เป็ด, เนื้อ, ดิบ', 199, 13.4, 0, 16.2, NULL, 0, NULL, 0, 100),
('แคบหมู', 593, 58.4, 0, 39.88, NULL, 0, NULL, NULL, 100),
('แคบหมู, ไม่มีมัน', 515, 56.4, 11.5, 27, NULL, 0, NULL, NULL, 100),
('แย้, ย่าง, รวมกระดูก', 249, 47.6, 0.3, 6.4, 405, 0, NULL, 0, 100),
('แย้, แห้ง, รวมกระดูก', 317, 67, 0, 5.4, NULL, 0, NULL, 0, 100),
('แฮม, หมู, ทอด', 262, 35.8, 0, 13.2, NULL, 0, NULL, NULL, 100),
('แฮม, ไก่, รมควัน', 192, 27.98, 0.62, 8.61, NULL, 0, NULL, NULL, 100),
('ไก่, กัน, ย่าง', 373, 16.97, 17.5, 26.13, 603, 0, 132, 0, 100),
('ไก่, ข้อเข่า, ต้ม', 196, 20.57, 0, 12.6, 104, 0, NULL, 0, 100),
('ไก่, ข้อเข่า, ทอด', 323, 40.1, 0.75, 17.75, 262, 0, NULL, 0, 100),
('ไก่, ตับ, ทอด', 239, 28.3, 3, 12.6, 77, 0, 591, 0, 100),
('ไก่, ตุ่น', 180, 18.9, 2.7, 10.3, 441, 0, NULL, 0.5, 100),
('ไก่, ทั้งตัว, ต้ม', 241, 22.9, 0, 16.6, 126, 0, 123, 0, 100),
('ไก่, น่อง, ต้ม', 206, 23.5, 0, 12.4, 149, 0, 165, 0, 100),
('ไก่, น่อง, ทอด', 203, 25.5, 0, 11.2, 198, 0, 185, 0, 100),
('ไก่, บด, ย่าง', 241, 25.2, 0, 15.4, 487, 0, NULL, 0.7, 100),
('ไก่, ปีก, ดิบ', 217, 16.9, 0, 16.6, 106, 0, 97, 0, 100),
('ไก่, ปีก, ต้ม', 261, 20.6, 0, 19.8, 118, 0, 179, 0, 100),
('ไก่, ปีก, ทอด', 290, 27.6, 0, 19.9, 111, 0, 196, 0, 100),
('ไก่, ย่าง', 184, 29.65, 0.45, 6.95, 546, 0, 151, 0.7, 100),
('ไก่, สะโพก, ดิบ', 212, 15.6, 2.2, 15.6, 108, 0, 58, 0, 100),
('ไก่, สะโพก, ต้ม', 242, 21.1, 2, 16.6, 124, 0, 100, 0, 100),
('ไก่, สะโพก, ทอด', 239, 27.9, 0, 14.2, 216, 0, 121, 0, 100),
('ไก่, หนัง, ทอด', 578, 33.74, 16.55, 41.86, 1168, 0, 34, 0, 100),
('ไก่, อก, รวมหนัง, ต้ม', 193, 28.6, 0, 8.7, 80, 0, 82, 0, 100),
('ไก่, อก, รวมหนัง, ทอด', 234, 35.7, 0, 10.1, 98, 0, 98, 0, 100)
) AS v(food_name, calories, protein, carbs, fat, sodium, sugar, cholesterol, fiber_g, serving_quantity)
JOIN cleangoal.dishes d
  ON d.dish_name = v.food_name
JOIN cleangoal.dish_categories dc
  ON dc.dish_category_id = d.dish_category_id
 AND dc.category_name = 'ThaiFCD import — วัตถุดิบ'
ON CONFLICT (food_name) DO UPDATE SET
    food_type    = EXCLUDED.food_type,
    calories     = EXCLUDED.calories,
    protein      = EXCLUDED.protein,
    carbs        = EXCLUDED.carbs,
    fat          = EXCLUDED.fat,
    sodium       = EXCLUDED.sodium,
    sugar        = EXCLUDED.sugar,
    cholesterol  = EXCLUDED.cholesterol,
    fiber_g      = EXCLUDED.fiber_g,
    serving_quantity = EXCLUDED.serving_quantity,
    serving_unit_id = EXCLUDED.serving_unit_id,
    dish_id      = EXCLUDED.dish_id,
    deleted_at   = NULL,
    updated_at   = NOW();

-- Ingredients foods batch 2/2

INSERT INTO cleangoal.foods (
    food_name, food_type, calories, protein, carbs, fat, sodium, sugar, cholesterol, fiber_g,
    serving_quantity, serving_unit_id, dish_id,
    updated_at
)
SELECT
    v.food_name,
    'raw_ingredient'::cleangoal.food_type,
    v.calories, v.protein, v.carbs, v.fat, v.sodium, v.sugar, v.cholesterol,
    COALESCE(v.fiber_g, 0),
    v.serving_quantity,
    (SELECT unit_id FROM cleangoal.units WHERE lower(name) = 'g' LIMIT 1),
    d.dish_id,
    NOW()
FROM (
    VALUES
('ไก่, เนื้อ, ดิบ', 186, 17.3, 1.4, 12.4, 90, 0, 81, 0, 100),
('ไก่, โครง, ชุปแป้งทอด', 375, 19.13, 17.8, 25.27, NULL, 0, NULL, NULL, 100),
('ไก่ป่า, ปีก, เนื้อและหนัง ดิบ', 187, 22.1, 0, 11, NULL, 0, NULL, 0, 100),
('ไก่ป่า, สะโพก, เนื้อและ หนัง, ดิบ', 218, 20.2, 0, 15.2, NULL, 0, NULL, 0, 100),
('ไก่ป่า, อก, เนื้อและหนัง ดิบ', 178, 24.3, 0, 9, NULL, 0, NULL, 0, 100),
('ไก่ยอ, ทอด', 342, 11.23, 16.43, 25.73, NULL, 0, NULL, NULL, 100),
('ไก่หยอง', 353, 38.18, 44.04, 2.63, NULL, 0, NULL, NULL, 100),
('ไก่เชียง, ทอด, ไม่ใส่นำมัน', 545, 14.65, 33.04, 39.28, 946, 0, 43, 0.6, 100),
('ไส้กรอก, หมู, ทอด', 272, 12.7, 8.3, 20.7, 680, 0, NULL, 1, 100),
('ไส้ถั่ว, ย่าง', 364, 18.45, 6.46, 29.33, NULL, 0, NULL, NULL, 100)
) AS v(food_name, calories, protein, carbs, fat, sodium, sugar, cholesterol, fiber_g, serving_quantity)
JOIN cleangoal.dishes d
  ON d.dish_name = v.food_name
JOIN cleangoal.dish_categories dc
  ON dc.dish_category_id = d.dish_category_id
 AND dc.category_name = 'ThaiFCD import — วัตถุดิบ'
ON CONFLICT (food_name) DO UPDATE SET
    food_type    = EXCLUDED.food_type,
    calories     = EXCLUDED.calories,
    protein      = EXCLUDED.protein,
    carbs        = EXCLUDED.carbs,
    fat          = EXCLUDED.fat,
    sodium       = EXCLUDED.sodium,
    sugar        = EXCLUDED.sugar,
    cholesterol  = EXCLUDED.cholesterol,
    fiber_g      = EXCLUDED.fiber_g,
    serving_quantity = EXCLUDED.serving_quantity,
    serving_unit_id = EXCLUDED.serving_unit_id,
    dish_id      = EXCLUDED.dish_id,
    deleted_at   = NULL,
    updated_at   = NOW();

-- Beverage dishes

INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'กาแฟปรุงสำเร็จรูป, ผง',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q35'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'ชานม, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q40'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'นมถั่วเหลือง, ยูเอชที, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q10'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำกระเจี้ยบ, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q11'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำขิง, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q44'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำตาลสด, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q46'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำนมข้าวโพด, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q49'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำฝรั่ง 100%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q47'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำฝรั่ง 25%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q48'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำมะพร้าว, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q20'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำมะม่วง, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q50'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำมะเขือเทศ, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q18'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำมังคุด, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q51'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำรากบัว, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q52'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำลิ้นจี่ 25%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q24'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำว่านหางจระเข้, กระป๋อง, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q25'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำสตรอเบอรี่ 25%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q54'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำสับปะรด, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q55'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำส้ม 100%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q27'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำส้ม 15%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q57'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำส้ม 25%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q56'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำองุ่น 100%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q34'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำองุ่น 25%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q59'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำเก็กฮวย, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q43'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำเฉาก๊วย',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q45'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'น้ำเสาวรส 25%, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q31'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เครื่องดื่มข้าวกล้องไรซ์เบอร์รี่, ต่อ 100 มล.',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q36'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เครื่องดื่มนมถั่วเหลือง, ผสมไวท์มอลต์',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q38'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เครื่องดื่มนมถั่วเหลือง, เสริมช็อกโกมอลต์',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q37'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;


INSERT INTO cleangoal.dishes (dish_name, dish_category_id, canonical_food_type, cuisine, description)
SELECT 'เครื่องดื่มรสช็อกโกแลต, ผง',
       dc.dish_category_id,
       'beverage'::cleangoal.food_type,
       'Thai',
       'ThaiFCD Q6'
FROM cleangoal.dish_categories dc
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND dc.canonical_food_type = 'beverage'::cleangoal.food_type
ON CONFLICT (dish_name, dish_category_id) DO NOTHING;

-- Beverage foods batch 1/1

INSERT INTO cleangoal.foods (
    food_name, food_type, calories, protein, carbs, fat, sodium, sugar, cholesterol, fiber_g,
    serving_quantity, serving_unit_id, dish_id,
    updated_at
)
SELECT
    v.food_name,
    'beverage'::cleangoal.food_type,
    v.calories, v.protein, v.carbs, v.fat,
    NULL,
    v.sugar,
    NULL,
    COALESCE(v.fiber_g, 0),
    100,
    (SELECT unit_id FROM cleangoal.units WHERE lower(name) = 'ml' LIMIT 1),
    d.dish_id,
    NOW()
FROM (
    VALUES
('กาแฟปรุงสำเร็จรูป, ผง', 'Q35', 389, 9.08, 71.38, 6.49, 40.83, 0),
('ชานม, ต่อ 100 มล.', 'Q40', 40, 1.68, 5.72, 1.1, 3.5, 0),
('นมถั่วเหลือง, ยูเอชที, ต่อ 100 มล.', 'Q10', 79, 2.9, 8.98, 3.34, 8.3, 0),
('น้ำกระเจี้ยบ, ต่อ 100 มล.', 'Q11', 60, 0.04, 14.94, 0.03, 13.29, 0),
('น้ำขิง, ต่อ 100 มล.', 'Q44', 28, 0, 7.08, 0, 7.6, 0),
('น้ำตาลสด, ต่อ 100 มล.', 'Q46', 77, 0.21, 18.94, 0, NULL, 0),
('น้ำนมข้าวโพด, ต่อ 100 มล.', 'Q49', 45, 1.05, 8.02, 0.77, 8.2, 0),
('น้ำฝรั่ง 100%, ต่อ 100 มล.', 'Q47', 57, 0.1, 0, 0, 12.28, 0),
('น้ำฝรั่ง 25%, ต่อ 100 มล.', 'Q48', 37, 0.1, 0, 0, 9.6, 0),
('น้ำมะพร้าว, ต่อ 100 มล.', 'Q20', 28, 0.09, 6.62, 0.1, 5.77, 0),
('น้ำมะม่วง, ต่อ 100 มล.', 'Q50', 50, 0.2, 11.7, 0.2, 11.68, 0),
('น้ำมะเขือเทศ, ต่อ 100 มล.', 'Q18', 34, 0.66, 7.06, 0.23, 3.65, 0),
('น้ำมังคุด, ต่อ 100 มล.', 'Q51', 65, 0.3, 15.5, 0.04, 13.3, 0),
('น้ำรากบัว, ต่อ 100 มล.', 'Q52', 37, 0, 0, 0, 8.9, 0),
('น้ำลิ้นจี่ 25%, ต่อ 100 มล.', 'Q24', 53, 0.12, 12.97, 0.02, 12.25, 0),
('น้ำว่านหางจระเข้, กระป๋อง, ต่อ 100 มล.', 'Q25', 49, 0.04, 10.68, 0.64, NULL, 0),
('น้ำสตรอเบอรี่ 25%, ต่อ 100 มล.', 'Q54', 43, 0, 10.55, 0, 10.55, 0),
('น้ำสับปะรด, ต่อ 100 มล.', 'Q55', 71, 0.3, 17.1, 0, 13.38, 0),
('น้ำส้ม 100%, ต่อ 100 มล.', 'Q27', 57, 0.68, 13.25, 0.09, 12.16, 0),
('น้ำส้ม 15%, ต่อ 100 มล.', 'Q57', 70, 0.15, 17.15, 0, 16.26, 0),
('น้ำส้ม 25%, ต่อ 100 มล.', 'Q56', 39, 0.1, 9.38, 0, 10.51, 0),
('น้ำองุ่น 100%, ต่อ 100 มล.', 'Q34', 69, 0.2, 16.97, 0, 13.45, 0),
('น้ำองุ่น 25%, ต่อ 100 มล.', 'Q59', 51, 0, 12.75, 0, 12.7, 0),
('น้ำเก็กฮวย, ต่อ 100 มล.', 'Q43', 42, 0, 10.53, 0, 11.16, 0),
('น้ำเฉาก๊วย', 'Q45', 27, 0, 6.76, 0, 6.9, 0),
('น้ำเสาวรส 25%, ต่อ 100 มล.', 'Q31', 59, 0.21, 14.31, 0.03, 11.47, 0),
('เครื่องดื่มข้าวกล้องไรซ์เบอร์รี่, ต่อ 100 มล.', 'Q36', 415, 20.7, 58.96, 10.08, NULL, 0),
('เครื่องดื่มนมถั่วเหลือง, ผสมไวท์มอลต์', 'Q38', 424, 11.18, 0, 11.47, NULL, 0),
('เครื่องดื่มนมถั่วเหลือง, เสริมช็อกโกมอลต์', 'Q37', 433, 11.03, 0, 11.87, NULL, 0),
('เครื่องดื่มรสช็อกโกแลต, ผง', 'Q6', 400, 12.01, 74.13, 6.11, NULL, 0)
) AS v(food_name, food_code, calories, protein, carbs, fat, sugar, fiber_g)
JOIN cleangoal.dishes d ON d.dish_name = v.food_name
JOIN cleangoal.dish_categories dc
  ON dc.dish_category_id = d.dish_category_id
 AND dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
ON CONFLICT (food_name) DO UPDATE SET
    food_type    = EXCLUDED.food_type,
    calories     = EXCLUDED.calories,
    protein      = EXCLUDED.protein,
    carbs        = EXCLUDED.carbs,
    fat          = EXCLUDED.fat,
    sugar        = EXCLUDED.sugar,
    fiber_g      = EXCLUDED.fiber_g,
    serving_quantity = EXCLUDED.serving_quantity,
    serving_unit_id = EXCLUDED.serving_unit_id,
    dish_id      = EXCLUDED.dish_id,
    deleted_at   = NULL,
    updated_at   = NOW();


-- Beverage dimension (water tracking): 100 ml per catalogue row nutrition basis.
INSERT INTO cleangoal.beverages (
    food_id, volume_ml, is_alcoholic, caffeine_mg, sugar_level_label, container_type
)
SELECT
    f.food_id,
    100,
    FALSE,
    0,
    CASE
        WHEN f.sugar IS NULL THEN 'ไม่ระบุ'
        WHEN f.sugar >= 12 THEN 'หวาน'
        WHEN f.sugar >= 6  THEN 'หวานปานกลาง'
        ELSE 'หวานน้อย'
    END,
    CASE WHEN f.food_name ILIKE '%กระป๋อง%' OR f.food_name ILIKE '%กระปอก%' THEN 'กระป๋อง' ELSE 'แก้ว' END
FROM cleangoal.foods f
JOIN cleangoal.dishes d ON d.dish_id = f.dish_id
JOIN cleangoal.dish_categories dc ON dc.dish_category_id = d.dish_category_id
WHERE dc.category_name = 'ThaiFCD import — เครื่องดื่ม'
  AND f.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM cleangoal.beverages b WHERE b.food_id = f.food_id
  );


INSERT INTO cleangoal.schema_migrations(version)
VALUES ('v28_thaifcd_import_foods')
ON CONFLICT (version) DO NOTHING;

COMMIT;
